import type { SchemaIR, CollectionSchema } from "@karnak19/pbkit"
import type { PbkitPlugin, PluginContext, PluginOutputFile } from "@karnak19/pbkit"

function pascalCase(name: string): string {
  return name
    .split(/[-_]/)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join("")
}

function singularize(name: string): string {
  if (name.endsWith("ies")) return name.slice(0, -3) + "y"
  if (name.endsWith("ses")) return name.slice(0, -2)
  if (name.endsWith("s") && !name.endsWith("ss")) return name.slice(0, -1)
  return name
}

function queryHooks(col: CollectionSchema): string[] {
  const p = pascalCase(col.name)
  const s = pascalCase(singularize(col.name))
  const c = JSON.stringify(col.name)
  const lines: string[] = []

  lines.push(`export function use${s}(pb: PbClient, id: string, options?: RequestOptions) {`)
  lines.push("  return useQuery({")
  lines.push(`    queryKey: [${c}, id],`)
  lines.push(`    queryFn: () => get${s}(pb, id, options),`)
  lines.push("  })")
  lines.push("}")
  lines.push("")
  lines.push(`export function use${p}(pb: PbClient, params?: ListParams) {`)
  lines.push("  return useQuery({")
  lines.push(`    queryKey: [${c}, params],`)
  lines.push(`    queryFn: () => list${p}(pb, params),`)
  lines.push("  })")
  lines.push("}")
  lines.push("")
  lines.push(`export function useFullList${p}(pb: PbClient, params?: ListParams) {`)
  lines.push("  return useQuery({")
  lines.push(`    queryKey: [${c}, "full", params],`)
  lines.push(`    queryFn: () => getFullList${p}(pb, params),`)
  lines.push("  })")
  lines.push("}")

  return lines
}

function mutationHooks(col: CollectionSchema): string[] {
  const p = pascalCase(col.name)
  const s = pascalCase(singularize(col.name))
  const c = JSON.stringify(col.name)
  const lines: string[] = []

  lines.push("")
  lines.push("")
  lines.push(`export function useCreate${s}(pb: PbClient) {`)
  lines.push("  const queryClient = useQueryClient()")
  lines.push("  return useMutation({")
  lines.push(`    mutationFn: (data: ${p}Create) => create${s}(pb, data),`)
  lines.push(`    onSuccess: () => queryClient.invalidateQueries({ queryKey: [${c}] }),`)
  lines.push("  })")
  lines.push("}")
  lines.push("")
  lines.push(`export function useUpdate${s}(pb: PbClient) {`)
  lines.push("  const queryClient = useQueryClient()")
  lines.push("  return useMutation({")
  lines.push(`    mutationFn: ({ id, data }: { id: string; data: ${p}Update }) => update${s}(pb, id, data),`)
  lines.push(`    onSuccess: (_data, variables) => {`)
  lines.push(`      queryClient.invalidateQueries({ queryKey: [${c}] })`)
  lines.push(`      queryClient.invalidateQueries({ queryKey: [${c}, variables.id] })`)
  lines.push("    },")
  lines.push("  })")
  lines.push("}")
  lines.push("")
  lines.push(`export function useDelete${s}(pb: PbClient) {`)
  lines.push("  const queryClient = useQueryClient()")
  lines.push("  return useMutation({")
  lines.push(`    mutationFn: (id: string) => delete${s}(pb, id),`)
  lines.push(`    onSuccess: () => queryClient.invalidateQueries({ queryKey: [${c}] }),`)
  lines.push("  })")
  lines.push("}")

  return lines
}

export function generateTanstack(ir: SchemaIR, ctx: PluginContext): string {
  const parts: string[] = []

  parts.push("// Generated by pbkit-tanstack — do not edit")
  parts.push("")
  parts.push('import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"')
  parts.push(`import type { PbClient, ListParams, RequestOptions } from "${ctx.typesImport}"`)
  parts.push(`import { ${ir.collections.flatMap(c => {
    const p = pascalCase(c.name)
    const s = pascalCase(singularize(c.name))
    return [`get${s}`, `list${p}`, `getFullList${p}`, `create${s}`, `update${s}`, `delete${s}`]
  }).join(", ")} } from "${ctx.sdkImport}"`)
  parts.push("")

  for (const col of ir.collections) {
    const p = pascalCase(col.name)
    parts.push(`// --- ${p} ---`)
    parts.push("")
    parts.push(...queryHooks(col))
    parts.push(...mutationHooks(col))
    parts.push("")
  }

  return parts.join("\n")
}

export const tanstackPlugin: PbkitPlugin = {
  name: "@karnak19/pbkit-tanstack-react-query",
  generate(ctx: PluginContext): PluginOutputFile[] {
    return [
      {
        path: "hooks.ts",
        content: generateTanstack(ctx.ir, ctx),
      },
    ]
  },
}
