import type { SchemaIR, CollectionSchema } from "../schema-parser";
import type { SdkGenerateOptions } from "./types";
import { isCollectionExcluded, isOperationEnabled, type CollectionsConfig } from "../config";

function pascalCase(name: string): string {
  return name
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function singularize(name: string): string {
  if (name.endsWith("ies")) return name.slice(0, -3) + "y";
  if (name.endsWith("ses")) return name.slice(0, -2);
  if (name.endsWith("s") && !name.endsWith("ss")) return name.slice(0, -1);
  return name;
}

function hasExpandType(col: CollectionSchema, ir: SchemaIR): boolean {
  return ir.relations.some((r) => r.collectionName === col.name);
}

function expandParam(col: CollectionSchema, ir: SchemaIR): string {
  if (!hasExpandType(col, ir)) return "RequestOptions";
  const p = pascalCase(col.name);
  return `Omit<RequestOptions, "expand"> & { expand?: ${p}Expand }`;
}

export function generateClientFile(options: SdkGenerateOptions = {}): string {
  const pbImport = options.pbImport ?? "pocketbase";
  const baseUrl = options.baseUrl ?? "";
  return [
    "// Generated by pbkit — do not edit",
    "",
    `import PocketBase from "${pbImport}"`,
    "",
    `export const client = new PocketBase(${JSON.stringify(baseUrl)})`,
    "export type PbClient = PocketBase",
    "",
  ].join("\n");
}

function crudFunctions(
  col: CollectionSchema,
  ir: SchemaIR,
  collections?: CollectionsConfig,
): string[] {
  const p = pascalCase(col.name);
  const s = pascalCase(singularize(col.name));
  const c = JSON.stringify(col.name);
  const ep = expandParam(col, ir);
  const lines: string[] = [];
  const op = (name: string) => isOperationEnabled(col.name, name as any, collections);

  if (op("get")) {
    lines.push(
      `export async function get${s}(id: string, options?: ${ep}, opts?: { client?: PbClient }): Promise<${p}Record> {`,
    );
    lines.push("  const pb = opts?.client ?? client");
    lines.push(`  return pb.collection(${c}).getOne(id, options) as Promise<${p}Record>`);
    lines.push("}");
    lines.push("");
  }
  if (op("getFirst")) {
    lines.push(
      `export async function getFirst${s}(filter: string, options?: ${ep}, opts?: { client?: PbClient }): Promise<${p}Record> {`,
    );
    lines.push("  const pb = opts?.client ?? client");
    lines.push(
      `  return pb.collection(${c}).getFirstListItem(filter, options) as Promise<${p}Record>`,
    );
    lines.push("}");
    lines.push("");
  }
  if (op("list")) {
    lines.push(
      `export async function list${p}(params?: ListParams, opts?: { client?: PbClient }): Promise<ListResult<${p}Record>> {`,
    );
    lines.push("  const pb = opts?.client ?? client");
    lines.push(
      `  return pb.collection(${c}).getList(params?.page, params?.perPage, params) as Promise<ListResult<${p}Record>>`,
    );
    lines.push("}");
    lines.push("");
  }
  if (op("getFullList")) {
    lines.push(
      `export async function getFullList${p}(params?: ListParams, opts?: { client?: PbClient }): Promise<${p}Record[]> {`,
    );
    lines.push("  const pb = opts?.client ?? client");
    lines.push(`  return pb.collection(${c}).getFullList(params) as Promise<${p}Record[]>`);
    lines.push("}");
    lines.push("");
  }
  if (op("create")) {
    lines.push(
      `export async function create${s}(data: ${p}Create, opts?: { client?: PbClient }): Promise<${p}Record> {`,
    );
    lines.push("  const pb = opts?.client ?? client");
    lines.push(`  return pb.collection(${c}).create(data) as Promise<${p}Record>`);
    lines.push("}");
    lines.push("");
  }
  if (op("update")) {
    lines.push(
      `export async function update${s}(id: string, data: ${p}Update, opts?: { client?: PbClient }): Promise<${p}Record> {`,
    );
    lines.push("  const pb = opts?.client ?? client");
    lines.push(`  return pb.collection(${c}).update(id, data) as Promise<${p}Record>`);
    lines.push("}");
    lines.push("");
  }
  if (op("delete")) {
    lines.push(
      `export async function delete${s}(id: string, opts?: { client?: PbClient }): Promise<true> {`,
    );
    lines.push("  const pb = opts?.client ?? client");
    lines.push(`  await pb.collection(${c}).delete(id)`);
    lines.push("  return true");
    lines.push("}");
    lines.push("");
  }

  return lines;
}

function authFunctions(col: CollectionSchema): string[] {
  const p = pascalCase(col.name);
  const s = pascalCase(singularize(col.name));
  const c = JSON.stringify(col.name);
  const lines: string[] = [];

  lines.push(
    `export async function auth${s}WithPassword(usernameOrEmail: string, password: string, opts?: { client?: PbClient }): Promise<${p}Record> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(
    `  const result = await pb.collection(${c}).authWithPassword(usernameOrEmail, password)`,
  );
  lines.push(`  return result.record as unknown as ${p}Record`);
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function auth${s}WithOAuth2(provider: string, code: string, codeVerifier: string, redirectUrl: string, opts?: { client?: PbClient }): Promise<${p}Record> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(
    `  const result = await pb.collection(${c}).authWithOAuth2Code(provider, code, codeVerifier, redirectUrl)`,
  );
  lines.push(`  return result.record as unknown as ${p}Record`);
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function auth${s}WithOTP(otpId: string, password: string, opts?: { client?: PbClient }): Promise<${p}Record> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(`  const result = await pb.collection(${c}).authWithOTP(otpId, password)`);
  lines.push(`  return result.record as unknown as ${p}Record`);
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function request${s}PasswordReset(email: string, opts?: { client?: PbClient }): Promise<true> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(`  await pb.collection(${c}).requestPasswordReset(email)`);
  lines.push("  return true");
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function confirm${s}PasswordReset(token: string, password: string, passwordConfirm: string, opts?: { client?: PbClient }): Promise<true> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(`  await pb.collection(${c}).confirmPasswordReset(token, password, passwordConfirm)`);
  lines.push("  return true");
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function request${s}Verification(email: string, opts?: { client?: PbClient }): Promise<true> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(`  await pb.collection(${c}).requestVerification(email)`);
  lines.push("  return true");
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function confirm${s}Verification(token: string, opts?: { client?: PbClient }): Promise<true> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(`  await pb.collection(${c}).confirmVerification(token)`);
  lines.push("  return true");
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function request${s}EmailChange(newEmail: string, opts?: { client?: PbClient }): Promise<true> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(`  await pb.collection(${c}).requestEmailChange(newEmail)`);
  lines.push("  return true");
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function confirm${s}EmailChange(token: string, password: string, opts?: { client?: PbClient }): Promise<true> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(`  await pb.collection(${c}).confirmEmailChange(token, password)`);
  lines.push("  return true");
  lines.push("}");
  lines.push("");
  lines.push(
    `export async function refresh${s}(opts?: { client?: PbClient }): Promise<${p}Record> {`,
  );
  lines.push("  const pb = opts?.client ?? client");
  lines.push(`  const result = await pb.collection(${c}).authRefresh()`);
  lines.push(`  return result.record as unknown as ${p}Record`);
  lines.push("}");
  lines.push("");

  return lines;
}

export function generateSdk(
  ir: SchemaIR,
  options: SdkGenerateOptions & { collections?: CollectionsConfig } = {},
): string {
  const typesImport = options.typesImport ?? "./types.gen";

  const cols = ir.collections.filter((c) => !isCollectionExcluded(c.name, options.collections));

  const typeImports = cols.flatMap((c) => {
    const p = pascalCase(c.name);
    const imports = [`${p}Record`, `${p}Create`, `${p}Update`];
    if (hasExpandType(c, ir)) imports.push(`${p}Expand`);
    return imports;
  });

  const parts: string[] = [];

  parts.push("// Generated by pbkit — do not edit");
  parts.push("");
  parts.push(`import { client, type PbClient } from "./client.gen"`);
  parts.push(`import type { ${typeImports.join(", ")} } from "${typesImport}"`);
  parts.push("");
  parts.push("export interface ListResult<T> {");
  parts.push("  page: number");
  parts.push("  perPage: number");
  parts.push("  totalItems: number");
  parts.push("  totalPages: number");
  parts.push("  items: T[]");
  parts.push("}");
  parts.push("");
  parts.push("export interface ListParams {");
  parts.push("  page?: number");
  parts.push("  perPage?: number");
  parts.push("  sort?: string");
  parts.push("  filter?: string");
  parts.push("  expand?: string");
  parts.push("  fields?: string");
  parts.push("}");
  parts.push("");
  parts.push("export interface RequestOptions {");
  parts.push("  expand?: string");
  parts.push("  filter?: string");
  parts.push("  sort?: string");
  parts.push("  fields?: string");
  parts.push("}");
  parts.push("");

  for (const col of cols) {
    const p = pascalCase(col.name);
    parts.push(`// --- ${p} ---`);
    parts.push("");
    parts.push(...crudFunctions(col, ir, options.collections));
    if (col.type === "auth") {
      parts.push(...authFunctions(col));
    }
  }

  return parts.join("\n");
}
