import type { SchemaIR, CollectionSchema } from "@karnak19/pbkit";
import type { PbkitPlugin, PluginContext, PluginOutputFile } from "@karnak19/pbkit";
import { isCollectionExcluded, pascalCase } from "@karnak19/pbkit";

function subscribeFunction(col: CollectionSchema): string[] {
  const p = pascalCase(col.name);
  const c = JSON.stringify(col.name);
  const fnName = `subscribeTo${p}`;
  const recordType = `${p}Record`;

  const lines: string[] = [];

  lines.push(`export async function ${fnName}(`);
  lines.push(`  callback: (event: RealtimeEvent<${recordType}>) => void,`);
  lines.push(`  options?: { filter?: string; id?: string },`);
  lines.push(`): Promise<() => Promise<void>> {`);
  lines.push(`  const target = options?.id ?? "*"`);
  lines.push(`  return client.collection(${c}).subscribe(target, (e) => {`);
  lines.push(`    callback({ action: e.action as RealtimeAction, record: e.record as ${recordType} })`);
  lines.push(`  }, { filter: options?.filter })`);
  lines.push(`}`);
  lines.push("");

  return lines;
}

export function generateRealtime(ir: SchemaIR, ctx: PluginContext): string {
  const parts: string[] = [];
  const cols = ir.collections.filter((c) => !isCollectionExcluded(c.name, ctx.collections));

  const typeImports = cols.map((c) => `${pascalCase(c.name)}Record`).sort();

  parts.push("// Generated by pbkit-realtime — do not edit");
  parts.push("");
  parts.push(`import { client } from "./client.gen"`);
  if (typeImports.length > 0) {
    parts.push(`import type { ${typeImports.join(", ")} } from "${ctx.typesImport}"`);
  }
  parts.push("");
  parts.push(`export type RealtimeAction = "create" | "update" | "delete"`);
  parts.push("");
  parts.push(`export interface RealtimeEvent<T> {`);
  parts.push(`  action: RealtimeAction`);
  parts.push(`  record: T`);
  parts.push(`}`);
  parts.push("");

  for (const col of cols) {
    const p = pascalCase(col.name);
    parts.push(`// --- ${p} ---`);
    parts.push("");
    parts.push(...subscribeFunction(col));
  }

  return parts.join("\n");
}

export const realtimePlugin: PbkitPlugin = {
  name: "@karnak19/pbkit-realtime",
  generate(ctx: PluginContext): PluginOutputFile[] {
    return [
      {
        path: "realtime.gen.ts",
        content: generateRealtime(ctx.ir, ctx),
      },
    ];
  },
};
