import { describe, test, expect } from "bun:test";
import { parseJson } from "@karnak19/pbkit";
import type { PluginContext } from "@karnak19/pbkit";
import { generateRealtime, realtimePlugin } from "../generate";
import fullSchema from "./fixtures/full-schema.json";

const ir = parseJson(fullSchema);
const ctx = {
  ir,
  typesImport: "./types.gen",
  sdkImport: "./sdk.gen",
} satisfies PluginContext;

describe("generateRealtime", () => {
  const output = generateRealtime(ir, ctx);

  test("imports client from client.gen", () => {
    expect(output).toContain('import { client } from "./client.gen"');
  });

  test("imports record types from configurable path", () => {
    expect(output).toContain('from "./types.gen"');
    expect(output).toContain("ArticlesRecord");
    expect(output).toContain("CommentsRecord");
    expect(output).toContain("UsersRecord");
    expect(output).toContain("CategoriesRecord");
  });

  test("uses configurable types import path", () => {
    const custom = generateRealtime(ir, {
      ...ctx,
      typesImport: "@karnak19/pbkit/types",
    });
    expect(custom).toContain('from "@karnak19/pbkit/types"');
  });

  test("exports RealtimeAction type", () => {
    expect(output).toContain('export type RealtimeAction = "create" | "update" | "delete"');
  });

  test("exports RealtimeEvent interface", () => {
    expect(output).toContain("export interface RealtimeEvent<T>");
    expect(output).toContain("action: RealtimeAction");
    expect(output).toContain("record: T");
  });

  test("generates async subscribe function per collection", () => {
    expect(output).toContain("export async function subscribeToArticles(");
    expect(output).toContain("export async function subscribeToComments(");
    expect(output).toContain("export async function subscribeToCategories(");
    expect(output).toContain("export async function subscribeToUsers(");
  });

  test("subscribe function accepts typed callback", () => {
    expect(output).toContain("callback: (event: RealtimeEvent<ArticlesRecord>) => void");
    expect(output).toContain("callback: (event: RealtimeEvent<CommentsRecord>) => void");
  });

  test("subscribe function accepts options with filter and id", () => {
    expect(output).toContain("options?: { filter?: string; id?: string }");
  });

  test("subscribe function returns Promise of unsubscribe function", () => {
    expect(output).toContain("): Promise<() => void>");
  });

  test("uses client.collection with correct name", () => {
    expect(output).toContain('client.collection("articles")');
    expect(output).toContain('client.collection("comments")');
    expect(output).toContain('client.collection("users")');
    expect(output).toContain('client.collection("categories")');
  });

  test("defaults target to * when no id provided", () => {
    expect(output).toContain('const target = options?.id ?? "*"');
  });

  test("casts event action and record", () => {
    expect(output).toContain("e.action as RealtimeAction");
    expect(output).toContain("e.record as ArticlesRecord");
  });

  test("passes filter option to subscribe", () => {
    expect(output).toContain("{ filter: options?.filter }");
  });

  test("snapshot", () => {
    expect(output).toMatchSnapshot();
  });

  test("skips excluded collections", () => {
    const excluded = generateRealtime(ir, {
      ...ctx,
      collections: { comments: { exclude: true } },
    });
    expect(excluded).not.toContain("subscribeToComments");
    expect(excluded).not.toContain("CommentsRecord");
    expect(excluded).toContain("subscribeToArticles");
  });
});

describe("realtimePlugin", () => {
  test("has correct name", () => {
    expect(realtimePlugin.name).toBe("@karnak19/pbkit-realtime");
  });

  test("generates realtime.gen.ts file", () => {
    const files = realtimePlugin.generate(ctx);
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe("realtime.gen.ts");
    expect(files[0].content).toContain("subscribeToArticles");
  });
});

describe("edge cases", () => {
  test("handles empty schema", () => {
    const emptyIr = parseJson([]);
    const output = generateRealtime(emptyIr, ctx);
    expect(output).toContain("Generated by pbkit-realtime");
    expect(output).toContain("RealtimeAction");
    expect(output).toContain("RealtimeEvent");
    expect(output).not.toContain("subscribeTo");
    expect(output).not.toContain("import type");
  });

  test("handles collection names with separators", () => {
    const schema = [
      {
        id: "_pbc_beta_feedback",
        name: "beta_feedback",
        type: "base",
        system: false,
        fields: [
          { id: "text_id", name: "id", type: "text", system: true, required: true },
          { id: "text_title", name: "title", type: "text", system: false, required: true },
        ],
      },
    ];
    const output = generateRealtime(parseJson(schema), ctx);
    expect(output).toContain("subscribeToBetaFeedback");
    expect(output).toContain("BetaFeedbackRecord");
    expect(output).toContain('client.collection("beta_feedback")');
  });
});
